use std::{
    collections::HashMap,
    env, fs,
    path::{Path, PathBuf},
};

fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf29ce484222325u64;
    for &byte in bytes {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let shader_dir = manifest_dir.join("shaders");
    println!("cargo:rerun-if-changed={}", shader_dir.display());

    let mut shaders = fs::read_dir(&shader_dir)
        .unwrap_or_else(|err| panic!("reading {}: {err}", shader_dir.display()))
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("spv"))
        .collect::<Vec<_>>();
    shaders.sort();

    let mut names_by_signature = HashMap::new();
    let mut registry = Vec::with_capacity(shaders.len());
    for path in shaders {
        println!("cargo:rerun-if-changed={}", path.display());
        let bytes =
            fs::read(&path).unwrap_or_else(|err| panic!("reading {}: {err}", path.display()));
        let signature = fnv1a64(&bytes);
        let name = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .unwrap_or_else(|| panic!("shader path is not valid UTF-8: {}", path.display()))
            .to_owned();
        if let Some(previous) = names_by_signature.insert(signature, name.clone()) {
            panic!("SPIR-V signature collision 0x{signature:016x}: {previous:?} and {name:?}");
        }
        registry.push((signature, name));
    }
    registry.sort_by_key(|(signature, _)| *signature);

    let mut generated = String::from(
        "// @generated by build.rs from shaders/*.spv; do not edit.\n\
         fn shader_debug_name(signature: u64) -> Option<&'static str> {\n\
         \x20   match signature {\n",
    );
    for (signature, name) in registry {
        generated.push_str(&format!("        0x{signature:016x} => Some({name:?}),\n"));
    }
    generated.push_str("        _ => None,\n    }\n}\n");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let output = out_dir.join(Path::new("shader_debug_registry.rs"));
    fs::write(&output, generated)
        .unwrap_or_else(|err| panic!("writing {}: {err}", output.display()));
}
