// Small-argument SLEEF 3.6.1 scalar xsinf_u1/xcosf_u1, adapted to GLSL.
// Copyright Naoki Shibata and contributors 2010 - 2021.
// Distributed under the Boost Software License, Version 1.0:
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
// Compensated FP32 arithmetic preserves the CPU oracle's rounding without
// requiring shaderFloat64. GLSL trig remains the large-argument fallback.
float trig_upper(float x) { return uintBitsToFloat(floatBitsToUint(x) & 0xfffff000u); }
vec2 trig_add(float x, float y) {
    precise float hi = x + y;
    precise float lo = (x - hi) + y;
    return vec2(hi, lo);
}
vec2 trig_add2(float x, float y) {
    precise float hi = x + y;
    precise float v = hi - x;
    precise float lo = (x - (hi - v)) + (y - v);
    return vec2(hi, lo);
}
vec2 trig_add(vec2 x, float y) {
    precise float hi = x.x + y;
    precise float lo = ((x.x - hi) + y) + x.y;
    return vec2(hi, lo);
}
vec2 trig_add(float x, vec2 y) {
    precise float hi = x + y.x;
    precise float lo = ((x - hi) + y.x) + y.y;
    return vec2(hi, lo);
}
vec2 trig_add2(vec2 x, float y) {
    precise vec2 r = trig_add2(x.x, y);
    r.y += x.y;
    return r;
}
vec2 trig_mul(vec2 x, vec2 y) {
    precise float xh = trig_upper(x.x), xl = x.x - xh;
    precise float yh = trig_upper(y.x), yl = y.x - yh;
    precise float hi = x.x * y.x;
    precise float lo = xh * yh - hi + xl * yh + xh * yl + xl * yl + x.x * y.y + x.y * y.x;
    return vec2(hi, lo);
}
float trig_mul_round(vec2 x, vec2 y) {
    precise float xh = trig_upper(x.x), xl = x.x - xh;
    precise float yh = trig_upper(y.x), yl = y.x - yh;
    precise float r = x.y * yh + xh * y.y + xl * yl + xh * yl + xl * yh + xh * yh;
    return r;
}
vec2 trig_square(vec2 x) {
    precise float xh = trig_upper(x.x), xl = x.x - xh;
    precise float hi = x.x * x.x;
    precise float lo = xh * xh - hi + (xh + xh) * xl + xl * xl + x.x * (x.y + x.y);
    return vec2(hi, lo);
}
float trig_poly(vec2 t) {
    precise vec2 s = trig_square(t);
    precise float u = 2.6083159809786593541503e-06;
    u = u * s.x - 0.0001981069071916863322258;
    u = u * s.x + 0.00833307858556509017944336;
    precise vec2 x = trig_add(1.0, trig_mul(trig_add(-0.166666597127914428710938, u * s.x), s));
    return trig_mul_round(t, x);
}
float trig_rint(float x) { return float(int(x < 0.0 ? x - 0.5 : x + 0.5)); }
float fp32_sin(float d) {
    if (!(abs(d) < 125.0)) return sin(d);
    if (d == 0.0) return d;
    precise float q = trig_rint(d * 0.31830988618379067154);
    precise float u = q * -3.1414794921875 + d;
    precise vec2 s = trig_add2(u, q * -0.00011315941810607910156);
    s = trig_add(s, q * -1.9841872589410058936e-09);
    u = trig_poly(s);
    return (int(q) & 1) != 0 ? -u : u;
}
float fp32_cos(float d) {
    if (!(abs(d) < 125.0)) return cos(d);
    d = abs(d);
    precise float a = d * 0.31830988618379067154 - 0.5;
    precise float q = trig_rint(a) * 2.0 + 1.0;
    precise vec2 s = trig_add2(d, q * (-3.1414794921875 * 0.5));
    s = trig_add2(s, q * (-0.00011315941810607910156 * 0.5));
    s = trig_add2(s, q * (-1.9841872589410058936e-09 * 0.5));
    precise float u = trig_poly(s);
    return (int(q) & 2) == 0 ? -u : u;
}
