#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) readonly buffer InputBuffer { float input_values[]; };
layout(set = 0, binding = 1, std430) buffer OutputBuffer { float output_values[]; };

layout(push_constant) uniform Push {
    uint len;
    uint first;
} pc;

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= pc.len) return;
    output_values[index] = pc.first != 0 ? input_values[index] : output_values[index] + input_values[index];
}
